### ISSUE TITLE
'Installer' object has no attribute 'remove-untracked'

### ISSUE THREAD

**Issue by Trashtalk217** [python-poetry/poetry-plugin-bundle#10]
I tried bundeling my project with this plugin and got the following error:

```
Trashtalk:project$ poetry bundle venv ~/Programming/project/test

  • Bundling evm_backend (0.1.0) into /home/nathan/Programming/project/test: Installing dependencies

  AttributeError

  'Installer' object has no attribute 'remove_untracked'

  at ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/poetry_bundle_plugin/bundlers/venv_bundler.py:133 in bundle
      129│             poetry.locker,
      130│             poetry.pool,
      131│             poetry.config,
      132│         )
    → 133│         installer.remove_untracked()
      134│         installer.use_executor(poetry.config.get("experimental.new-installer", False))
      135│ 
      136│         return_code = installer.run()
      137│         if return_code:
```

I don't know why this doesn't work, since I have a completely fresh install of both poetry and this plugin. I did some minor detective work and found out that `remove_untracked` doesn't exist in [this file](https://github.com/python-poetry/poetry/blob/master/src/poetry/installation/installer.py) at least. Should I downgrade to an earlier 1.2 pre-release?

**Comment by qlyoung** [comment]
This was fixed in https://github.com/python-poetry/poetry-plugin-bundle/pull/1 but this project hasn't had a new release on PyPI since then, so it doesn't work for any available poetry version :(
