### ISSUE TITLE
"Could not find a matching version of package poetry-plugin-bundle" on install

### ISSUE THREAD

**Issue by drone-ah** [python-poetry/poetry-plugin-bundle#17]
Hi,

Thanks for putting together this useful tool. I don't seem to be able to install it though, and get the following error.

`$ poetry --version
Poetry (version 1.2.0b1)
$ poetry plugin add poetry-plugin-bundle

Could not find a matching version of package poetry-plugin-bundle
`

Any ideas on how to resolve it?

Thanks,

**Comment by faizhasan** [comment]
try 
`poetry self add bundle`

**Comment by sbdelisle** [comment]
I think this might be a documentation error.  There's no published python package named `poetry-plugin-bundle`, but there is one named `poetry-bundle-plugin`.

**Comment by drone-ah** [comment]
Thank you both :) 

`poetry self add poetry-bundle-plugin` worked :D
