### ISSUE TITLE
Package not published to pypi.org

### ISSUE THREAD

**Issue by mistakenforzen** [python-poetry/poetry-plugin-bundle#80]
The latest (indeed only) version available on pypi.org is 0.1.0 from July 2021. This version is not compatible with poetry 1.2+. Following instructions on the readme to install using `pip` therefore results in a broken installation.

I'm working in an offline environment with a private pypi mirror, so installing with `poetry self add` isn't an option. Currently workaround is to manually install from downloaded wheel.

**Comment by dimbleby** [comment]
nonsense.  I expect you've typo'd something

https://pypi.org/project/poetry-plugin-bundle/#history

**Comment by mistakenforzen** [comment]
Ah, you're right. 🤦🏻 "bundle" and "plugin" were inverted. But you should be aware that this exists:

https://pypi.org/project/poetry-bundle-plugin/#history
