### ISSUE TITLE
Support for precompiled bundles

### ISSUE THREAD

**Issue by KineticCookie** [python-poetry/poetry-plugin-bundle#89]
Hi!
I have a specific use case and I am wondering if this is a right tool to use.

I have an Airflow instance which uses docker images to run tasks.
There docker images contain python bundles with task code.
After benchmarking the jobs, we found out that compilation of dependencies and project modules improves the run time. (i.e. `poetry install --compile` + `python -m compileall app`)

We can do it manually by running `compileall` in venv, but it seems hacky.

Is such use case within the scope of this plugin?
I think this feature will be a big benefit for short-lived code where startup time is crucial.

**Comment by radoering** [comment]
Resolved by #88
